### ISSUE TITLE
planner_ns/evaluation critics output debugging clues

### ISSUE THREAD

**Issue by artemiialessandrini** [locusrobotics/robot_navigation#56]
Hi, after getting an answer to [this](https://answers.ros.org/question/352740/move_base_flex-loading-dwb_local_planner-using-adapter-but-cannot-plan/) question about DWB_local_planner, I'd like to get some more information 
about `planner_ns/evaluation` output and the way to use it for debugging purposes.

Could you please briefly explain, what we expect to get there? 
I'm currently recieving this:
```
    scores: 
      - 
        name: "RotateToGoal"
        raw_score: 0.0
        scale: 1.0
      - 
        name: "Oscillation"
        raw_score: 0.0
        scale: 1.0
      - 
        name: "ObstacleFootprint"
        raw_score: 253.0
        scale: 0.000250000011874
      - 
        name: "GoalAlign"
        raw_score: 73.0
        scale: 0.00875000003725
    total: 0.702000021935
best_index: 9
worst_index: 26
---
```
